apiVersion: skaffold/v2beta29
kind: Config
build:
  tagPolicy:
    sha256:  {}
  artifacts:
    - image: gcr.io/mohamed-playground/frontend
      context: ./frontend/react/
      sync:
        infer:
          - '**/*.js'
    - image: gcr.io/mohamed-playground/storefront
      context: .
      jib:
        project: storefront
        type: gradle
    - image: gcr.io/mohamed-playground/comments
      context: .
      jib:
        project: comments
    - image: gcr.io/mohamed-playground/offers
      context: .
      jib:
        project: offers
    - image: gcr.io/mohamed-playground/pets
      context: .
      jib:
        project: pets
    - image: gcr.io/mohamed-playground/vendors
      context: .
      jib:
        project: vendors

deploy:
  #  kubectl:
  #    manifests:
  #      - k8s/base/*.yaml
  kustomize:
    paths:
      - k8s/overlays/local

