apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbms
spec:
  selector:
    matchLabels:
      app: sbms-jib
  replicas: 1
  template:
    metadata:
      labels:
        app: sbms-jib
    spec:
      containers:
        - name: sbms-jib
          image: gcr.io/mohamed-playground/sbms-jib
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
