apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: gcr.io/mohamed-playground/sbms-jib
      jib: {}
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
portForward:
  - resourceType: service
    resourceName: sbms
    port: 8080
    localPort: 9000
#  helm:
#    releases:
#      - name: spring-boot-jib
#        chartPath: helm
#        values:
#          image.repository: gcr.io/mohamed-playground/sbms-jib
#        setValues:
#          image.tag: ""
