apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: gcr.io/mohamed-playground/sbms-jib
      jib: {}
test:
  - image: gcr.io/mohamed-playground/sbms-jib
    structureTests:
      - ./structured-tests.yaml
portForward:
  - resourceType: service
    resourceName: sbms
    port: 8080
    localPort: 9000
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml

profiles:
### buildpacks profile
- name: pack
  build:
    artifacts:
    - image: gcr.io/mohamed-playground/sbms-jib
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
        env:
          - GOOGLE_RUNTIME_VERSION=17
### Helm profile
- name: helm
  deploy:
    helm:
      releases:
      - name: spring-boot-jib
        chartPath: helm
        artifactOverrides:
          image: gcr.io/mohamed-playground/sbms-jib
        imageStrategy:
          helm: {}
